// 크릿벤처스 포트폴리오 데이터
// n: 회사명(한국어 페이지) / ne: 영문명(영어 페이지, 없으면 n 사용)
// u: 홈페이지(빈 값이면 링크 없음) / r: 지역(kr|us) / g: 로고 파일명
// s: 섹터 키 / d: 주요 사업분야(한국어) / de: 주요 사업분야(영어)
// a: 추가 검색 별칭(한·영 혼용 가능)
//
// [주의] 회사명·링크·지역·로고는 crit.vc 실제 데이터.
//        섹터(s)와 설명(d/de), 영문명(ne)은 원본 사이트에 없어 회사 정보 기반으로 작성한 값이므로
//        검수 후 수정해 주세요.
window.PORTFOLIO_SECTORS = {
  game: "게임",
  content: "콘텐츠·엔터",
  ai: "AI·딥테크",
  commerce: "커머스·플랫폼",
  healthcare: "헬스케어",
  web3: "Web3·블록체인"
};
window.PORTFOLIO_SECTORS_EN = {
  game: "Game",
  content: "Content·Media",
  ai: "AI·Deep Tech",
  commerce: "Commerce·Platform",
  healthcare: "Healthcare",
  web3: "Web3·Blockchain"
};

window.PORTFOLIO = [
    { n: "하이퍼네트웍스", ne: "Hypernetworks", u: "https://hypernetworks.co.kr/", r: "kr", g: "portfolio_110", s: "content", d: "TikTok LIVE 크리에이터 에이전시", de: "TikTok LIVE creator agency", a: "hypernetworks 하이퍼네트웍스" },
    { n: "YUZUCO", u: "https://www.theyuzu.co/", r: "kr", g: "YUZUCO.svg", s: "commerce", d: "유자 기반 식음료 제조·유통", de: "Yuzu-based food & beverage maker", a: "유주코 유자 theyuzu" },
    { n: "벙커키즈", ne: "Bunkerkids", u: "", r: "kr", g: "portfolio_109", s: "content", d: "AI 캐릭터 채팅 기반 여성향 Live Fiction 플랫폼 'WHIF'", de: "AI character-chat female-oriented live-fiction platform 'WHIF'", a: "whif 벙커키즈 bunkerkids 위프" },
    { n: "Yoyogi Animation Group Inc.", ne: "Yoyogi Animation Group", u: "", r: "us", g: "portfolio_108", s: "content", d: "일본 IP 엔터테인먼트", de: "Japan IP entertainment", a: "요요기 yoyogi animation 요아니 yoani 우타이테" },
    { n: "스콘", ne: "SCON", u: "https://www.scon.company/", r: "kr", g: "portfolio_91", s: "content", d: "버추얼 IP 엔터테인먼트(버추얼 아이돌)", de: "Virtual IP entertainment studio", a: "미츄 meechu" },
    { n: "엑스와이지", ne: "XYZ", u: "https://xyzcorp.io/", r: "kr", g: "portfolio_85", s: "ai", d: "AI 서비스로봇·바리스타 로봇 개발사", de: "AI service robotics maker", a: "xyz", hl: 1, ho: 4 },
    { n: "But Beautiful", ne: "But Beautiful", u: "https://www.butbeautiful.co/", r: "us", g: "But Beautiful.jpg", s: "ai", d: "AI 네이티브 소셜 앱 '츄룹'", de: "AI-native social app 'Truloop'", a: "츄룹 truloop" },
    { n: "유비파이", ne: "UVify", u: "https://www.uvify.com/", r: "kr", g: "유비파이.png", s: "ai", d: "군집비행·라이트쇼 자율비행 드론 제조사", de: "Autonomous & swarm light-show drone maker", hl: 1, ho: 2 },
    { n: "Ologie", ne: "Ologie", u: "", r: "us", g: "ologie.png", s: "healthcare", d: "뉴욕 기반 K-뷰티 메디컬 미용 플랫폼", de: "NYC-based K-beauty medical aesthetics platform", a: "올로지" },
    { n: "Sopo", ne: "Sopo", u: "https://eatsopo.com/", r: "us", g: "portfolio_97", s: "commerce", d: "뉴욕 기반 한식 패스트캐주얼 브랜드", de: "NYC Korean fast-casual brand", a: "kkinee 끼니 소포" },
    { n: "Early Health", ne: "Early Health", u: "https://www.earlyhealth.com/", r: "us", g: "portfolio_99", s: "healthcare", d: "가정용 소변검사 기반 질병 조기진단", de: "At-home urine testing for early disease detection", a: "얼리헬스" },
    { n: "Noah's Farm", ne: "Noah's Farm", u: "https://noahs-farm.xyz/", r: "us", g: "noah's farm.jpg", s: "ai", d: "AI 기반 향료 분자·정밀 향미 R&D", de: "AI-driven flavor molecule R&D" },
    { n: "Artue", u: "https://artue.io/ko", r: "kr", g: "portfolio_107", s: "web3", d: "AI 감성 큐레이션 기반 아트 플랫폼·온체인 RWA", de: "AI emotional-curation art platform & on-chain RWA", a: "아르튜 art" },
    { n: "모비콘텐츠테크", ne: "Mobi Contents Tech", u: "https://en.mobicontentstech.com/", r: "kr", g: "portfolio_89", s: "commerce", d: "글로벌 K팝 팬덤 IP커머스 플랫폼", de: "Global K-pop fandom IP-commerce platform", a: "코코다이브 cokodive mobicontents" },
    { n: "Deep Into The", ne: "Deep Into The", u: "https://www.deepintothe.xyz/", r: "us", g: "portfolio_98", s: "ai", d: "IP 홀더용 AI 페르소나 엔진", de: "EQ-based AI persona engine for IP holders", a: "deepintothe 딥인투더" },
    { n: "펩", ne: "Pep", u: "", r: "kr", g: "펩.jpg", s: "game", d: "하이브리드 캐주얼 게임 개발사", de: "Hybrid casual game studio" },
    { n: "피유엠피", ne: "PUMP", u: "https://www.xingxingmobility.com/", r: "kr", g: "portfolio_94", s: "commerce", d: "공유 전동킥보드 도심 모빌리티", de: "Shared e-scooter urban mobility", a: "씽씽 xingxing pump 피유엠피" },
    { n: "위드포인츠", ne: "WithPoints", u: "https://www.withpoints.co.kr/", r: "kr", g: "portfolio_96", s: "ai", d: "3D 비전 기반 모듈형 로봇자동화 솔루션", de: "3D vision-based modular robotics automation" },
    { n: "Clink", ne: "Clink", u: "https://clink-official.co.jp/", r: "us", g: "clink.svg", s: "content", d: "인플루언서·디지털 마케팅 기업(일본)", de: "Influencer & digital marketing agency (Japan)", a: "클링크" },
    { n: "Meet48", u: "https://www.meet48.com/", r: "us", g: "portfolio_106", s: "web3", d: "블록체인 기반 아이돌 육성 플랫폼", de: "Blockchain-based idol nurturing platform", a: "밋48 meet48", hl: 1, ho: 4 },
    { n: "네이처라우드", ne: "Natureloud", u: "https://lyawell.com/", r: "kr", g: "portfolio_87", s: "commerce", d: "'이영애의 건강미식' 건강식품 커머스", de: "Health-food commerce brand", a: "이영애의 건강미식 lyawell" },
    { n: "뉴빌리티", ne: "Neubility", u: "https://www.neubility.ai/", r: "kr", g: "portfolio_84", s: "ai", d: "자율주행 배달로봇·RaaS 개발사", de: "Autonomous delivery robots & RaaS", hl: 1, ho: 3 },
    { n: "OpenLedger", u: "https://www.openledger.xyz/", r: "us", g: "portfolio_105", s: "web3", d: "POA 기반 탈중앙 AI 인프라", de: "Decentralized AI infrastructure (Via Proof-of-Contribution)", a: "오픈레저 open ledger" },
    { n: "AboveTech", u: "https://www.abovetech.io/", r: "kr", g: "portfolio_104", s: "ai", d: "AI 챗봇 '젠디' 등 B2C AI 서비스", de: "Consumer AI services incl. AI chatbot 'Gendi'", a: "어보브테크 gendi 젠디" },
    { n: "당근", ne: "Daangn", u: "https://about.daangn.com/", r: "kr", g: "portfolio_83", s: "commerce", d: "동네 기반 중고거래·로컬 생활 플랫폼", de: "Hyperlocal community marketplace", a: "당근마켓 karrot daangn", hl: 1, ho: 1 },
    { n: "Lo:Tech", u: "https://lo.tech/", r: "us", g: "portfolio_103", s: "web3", d: "가상자산 마켓메이킹(MMaaS)·시장 데이터 서비스", de: "Crypto market making (MMaaS) & market data services", a: "lotech 로테크 low observable technology" },
    { n: "Remix", u: "https://remix.gg/", r: "us", g: "portfolio_102", s: "game", d: "AI 기반 하이퍼캐주얼 게임 생성·배포 플랫폼", de: "AI-powered hypercasual game creation & distribution platform", a: "리믹스 farcade" },
    { n: "오프비트", ne: "Offbeat", u: "https://offbeatplay.com/", r: "kr", g: "오프비트.png", s: "game", d: "'전지적 독자 시점' IP 게임 개발 스튜디오", de: "Game studio for the Omniscient Reader's Viewpoint IP", hl: 1, ho: 3 },
    { n: "STL", ne: "STL", u: "https://start-today.co.kr/", r: "kr", g: "portfolio_92", s: "commerce", d: "이커머스 풀필먼트·크로스보더 물류", de: "E-commerce fulfillment & cross-border logistics", a: "스타트투데이 start today 에스티엘" },
    { n: "펫팜", ne: "PetPharm", u: "https://www.petpharm.kr/", r: "kr", g: "portfolio_82", s: "healthcare", d: "동물의약품 및 건기식 공급 동물약국 B2B 이커머스", de: "Animal pharmacies B2B e-commerce", a: "펫팜 Pet nutrition & healthcare" },
    { n: "퓨리오사AI", u: "https://furiosa.ai/", r: "kr", g: "portfolio_81", s: "ai", d: "AI 추론용 반도체(NPU) 설계", de: "AI inference semiconductor (NPU) design", a: "퓨리오사 furiosa ai", hl: 1, ho: 1 },
    { n: "원셀프월드", u: "https://1self.world/", r: "kr", g: "portfolio_80", s: "web3", d: "디지털 지갑 기반 마케팅 플랫폼 마이비(MyB)", de: "Digital wallet-based marketing platform MyB", a: "원셀프월드 1self world" },
    { n: "빌보드코리아", ne: "Billboard Korea", u: "https://billboard.co.kr/", r: "kr", g: "portfolio_90", s: "content", d: "K팝 음악·문화 미디어 채널", de: "K-pop music & culture media channel", a: "빌보드billboard" },
    { n: "일레븐플러스", ne: "11plus", u: "https://11plus.co/", r: "kr", g: "일레븐플러스.jpg", s: "content", d: "글로벌 축구 팬덤 커뮤니티 플랫폼", de: "Global football fandom community platform" },
    { n: "구루컴퍼니", ne: "Guru Company", u: "https://www.gurucompany.co.kr/", r: "kr", g: "구루컴퍼니.png", s: "content", d: "B2B 콘텐츠 플러그인 솔루션", de: "B2B content plugin solution", a: "보물섬" },
    { n: "비마이프렌즈", ne: "bemyfriends", u: "https://bemyfriends.com/", r: "kr", g: "portfolio_86", s: "content", d: "글로벌 팬덤 비즈니스 솔루션 '비스테이지'", de: "Global fandom solution 'b.stage'", a: "bstage 비스테이지", hl: 1 },
    { n: "Doppler Finance", u: "https://www.doppler.finance/", r: "us", g: "portfolio_us_15", s: "web3", d: "크립토 자산 수익 플랫폼", de: "Crypto asset yield platform" },
    { n: "콜리", ne: "Colley", u: "https://colley.kr/", r: "kr", g: "portfolio_93", s: "commerce", d: "IP 굿즈·덕질 올인원 플랫폼", de: "All-in-one IP merch & fandom platform" },
    { n: "Pixelverse", u: "https://pixelverse.xyz/", r: "us", g: "portfolio_us_5", s: "web3", d: "Web3 게임·메타버스", de: "Web3 game & metaverse" },
    { n: "Pryzm", ne: "Pryzm", u: "https://supervlabs.io/", r: "kr", g: "portfolio_77", s: "game", d: "게임 스튜디오 (구 슈퍼빌런랩스)", de: "Game studio (formerly Supervillain Labs)", a: "슈퍼빌런랩스 supervillain labs supervlabs 프리즘" },
    { n: "레보메드", ne: "REV-MED", u: "https://rev-med.co.kr/", r: "kr", g: "portfolio_88", s: "healthcare", d: "혈액·골수·지방세포 분리농축 재생의학", de: "Regenerative-medicine cell separation biotech" },
    { n: "D.TO", ne: "D.TO", u: "https://dtoaec.com/", r: "kr", g: "dto.svg", s: "ai", d: "건축가용 AI 기반 BIM·설계 자동화", de: "AI-powered BIM & design automation for architects", a: "디투" },
    { n: "프로메디우스", ne: "Promedius", u: "https://promedius.ai/ko", r: "kr", g: "portfolio_76", s: "healthcare", d: "AI 기반 의료영상 진단", de: "AI-based medical imaging diagnosis", hl: 1 },
    { n: "에이버튼", ne: "A Button", u: "https://www.abutton.com/", r: "kr", g: "portfolio_75", s: "game", d: "게임 개발 스타트업", de: "Game developer Startup", hl: 1, ho: 1 },
    { n: "Peaq", u: "https://www.peaq.network/", r: "us", g: "portfolio_us_3", s: "web3", d: "DePIN 블록체인 네트워크", de: "DePIN blockchain network", hl: 1, ho: 3 },
    { n: "브이에이게임즈", ne: "VA Games", u: "https://vagames.co.kr/", r: "kr", g: "portfolio_73", s: "game", d: "모바일 게임 개발사", de: "Mobile game developer" },
    { n: "팔레트", ne: "Palette", u: "https://www.pltt.xyz/", r: "kr", g: "portfolio_74", s: "content", d: "기업용 AI 광고·영상 제작 플랫폼", de: "AI ad & video content creation platform", a: "캡슐미디어 capsule" },
    { n: "바잉스퀘어", ne: "Buying Square", u: "https://official.buying-square.com/", r: "kr", g: "portfolio_72", s: "commerce", d: "디지털 도매 플랫폼", de: "Digital wholesale platform" },
    { n: "로커스", ne: "Locus", u: "https://locus.com/", r: "kr", g: "portfolio_71", s: "content", d: "애니메이션 제작 스튜디오", de: "Animation production studio" },
    { n: "에스씨엠티", ne: "SCMT", u: "", r: "kr", g: "에스씨엠티.png", s: "ai", d: "반도체 CMP 패드 제조", de: "Semiconductor CMP pad manufacturer" },
    { n: "지앤지프로덕션", ne: "GnG Production", u: "http://www.gngpro.co.kr/", r: "kr", g: "portfolio_70", s: "content", d: "드라마 제작·IP프랜차이즈", de: "Drama production & IP franchise" },
    { n: "피치스그룹코리아", ne: "Peaches Group Korea", u: "https://peachesoneuniverse.com/", r: "kr", g: "portfolio_69", s: "content", d: "카 컬처 라이프스타일 브랜드 '피치스'", de: "Car-culture lifestyle brand 'Peaches'" },
    { n: "브레이브컴퍼니", ne: "Brave Company", u: "https://www.bravecompany.kr/", r: "kr", g: "portfolio_66", s: "commerce", d: "크리에이터 기반 헬스케어 커머스", de: "Creator-based healthcare commerce", a: "브레이브컴퍼니" },
    { n: "신스타프리젠츠", ne: "Shinstar Presents", u: "https://www.shinstarr.com/", r: "kr", g: "portfolio_67", s: "content", d: "로봇키친(푸드테크)", de: "Robot kitchen (foodtech)" },
    { n: "Aark Digital", u: "https://aark.digital/", r: "us", g: "portfolio_us_13", s: "web3", d: "디파이(DeFi) 파생상품 거래", de: "DeFi derivatives trading" },
    { n: "Order of Meta Oy", u: "https://orderofmeta.com/", r: "kr", g: "portfolio_64", s: "game", d: "게임 개발사(핀란드)", de: "Game developer (Finland)" },
    { n: "MG Innovation Lab, Inc.", u: "https://www.globaleur.com/", r: "kr", g: "portfolio_63_v2", s: "commerce", d: "AI 기반 여행 솔루션 '글로벌리어'", de: "AI-based travel solution 'Globaleur'", a: "글로벌리어 globaleur" },
    { n: "SAGA", u: "https://www.saga.xyz/", r: "us", g: "portfolio_us_2", s: "web3", d: "블록체인 인프라 네트워크", de: "Blockchain infrastructure network", hl: 1, ho: 2 },
    { n: "MetaverseGo", u: "https://app.metaversego.gg/", r: "us", g: "portfolio_us_12", s: "web3", d: "Web3 게임 플랫폼", de: "Web3 game platform" },
    { n: "Artes Studio Ltd", u: "https://www.match-cash.com/", r: "kr", g: "portfolio_79", s: "game", d: "모바일 게임 개발사", de: "Mobile game developer" },
    { n: "KTX", u: "https://www.ktx.finance/", r: "us", g: "portfolio_us_11", s: "web3", d: "디파이(DeFi) 프로토콜", de: "DeFi protocol" },
    { n: "플럭서스", ne: "Fluxus", u: "https://www.fluxus.co.kr/", r: "kr", g: "fluxus.svg", s: "content", d: "글로벌 음악 유통·마케팅 테크", de: "Music distribution & marketing tech" },
    { n: "넛지헬스케어", ne: "Nudge Healthcare", u: "https://cashwalk.com/", r: "kr", g: "portfolio_61", s: "healthcare", d: "리워드 헬스케어 앱 '캐시워크'", de: "Reward healthcare app 'CASHWALK'", a: "cashwalk 캐시워크", hl: 1 },
    { n: "글로벌푸드테크", ne: "Global Foodtech", u: "https://globalfoodtech.net/", r: "kr", g: "globalfoodtech.svg", s: "commerce", d: "외식 예약·발주·결제 디지털 솔루션", de: "Restaurant reservation/ordering/payment solutions" },
    { n: "펀더풀", ne: "Funderful", u: "https://funderful.kr/", r: "kr", g: "portfolio_59", s: "content", d: "공연·문화 투자 크라우드펀딩", de: "Culture & performance investment crowdfunding" },
    { n: "포스크리에이티브파티", ne: "4th Creative Party", u: "http://www.4thparty.co.kr/", r: "kr", g: "portfolio_57", s: "content", d: "크리에이티브·콘텐츠 제작", de: "Creative & content production" },
    { n: "라라스테이션", ne: "Lala Station", u: "https://lalastations.com/", r: "kr", g: "portfolio_56", s: "content", d: "라이브 커머스 콘텐츠 플랫폼", de: "Live-commerce content platform" },
    { n: "Carbonated, Inc.", u: "https://www.carbonated.com/", r: "kr", g: "portfolio_62", s: "game", d: "모바일 게임 개발사", de: "Mobile game developer" },
    { n: "Pudgy Penguins", u: "https://pudgypenguins.com/", r: "us", g: "portfolio_us_1", s: "web3", d: "NFT IP·Web3 브랜드", de: "NFT IP & Web3 brand", hl: 1, ho: 1 },
    { n: "인덴트코퍼레이션", ne: "Indent Corporation", u: "https://indentcorp.com/", r: "kr", g: "portfolio_58", s: "commerce", d: "AI 기반 커머스 솔루션", de: "AI-based commerce solution" },
    { n: "Gomble", u: "https://gomble.io/", r: "us", g: "portfolio_us_4", s: "web3", d: "Web3 게임 스튜디오", de: "Web3 game studio" },
    { n: "에이베러", ne: "Abetter", u: "https://www.a-better.co.kr/", r: "kr", g: "portfolio_101", s: "commerce", d: "쿠팡·아마존 유통 전문 이커머스 기업", de: "Coupang/Amazon-focused e-commerce distribution company", a: "abetter 에이베러 dealsplus" },
    { n: "데이원드림", ne: "Day One Dream", u: "https://www.dayonedream.com/", r: "kr", g: "portfolio_78_v2", s: "content", d: "종합 엔터테인먼트", de: "Comprehensive entertainment company", a: "DOD 디오디", hl: 1 },
    { n: "뮤즈라이브", ne: "MUZLIVE", u: "https://www.muzlive.com/", r: "kr", g: "portfolio_55", s: "content", d: "음악 콘텐츠·키트 플랫폼", de: "Music content & kit platform" },
    { n: "런업컴퍼니", ne: "Runup Company", u: "https://runupcompany.com/", r: "kr", g: "portfolio_53", s: "content", d: "콘텐츠 제작·기획", de: "Content production & planning" },
    { n: "바이오리서치에이아이", ne: "BioResearch AI", u: "", r: "kr", g: "portfolio_50", s: "ai", d: "제약·바이오 특화 AI 데이터베이스", de: "Pharmaceutical & biotech-focused AI database" },
    { n: "브이원씨", ne: "V-1C", u: "https://clobe.ai/", r: "kr", g: "portfolio_51", s: "ai", d: "재무·회계 AI ERP '클로브AI'", de: "Financial & accounting AI ERP 'Clobe AI'", a: "clobe 클로브" },
    { n: "콘텐츠테크놀로지스", ne: "Contents Technologies", u: "https://contentstech.com/", r: "kr", g: "portfolio_52_v1", s: "content", d: "테크 기반 음악 기업 ", de: "Tech-driven music company", hl: 1 },
    { n: "Sygnal", u: "", r: "us", g: "portfolio_100", s: "web3", d: "소상공인·크리에이터용 노코드 AI 에이전트 플랫폼 'MiniMe'", de: "No-code AI agent (digital twin) platform for SMEs and creators", a: "시그널 sygnal xyz minime" },
    { n: "Jadu AR", u: "https://jadu.ar/", r: "us", g: "portfolio_us_6", s: "ai", d: "AR 플랫폼 기업", de: "AR platform company" },
    { n: "Metaworld Entertainment", u: "https://www.metaworldentertainment.io/", r: "us", g: "portfolio_us_9", s: "web3", d: "메타버스 엔터테인먼트", de: "Metaverse entertainment" },
    { n: "Spaceport", u: "https://www.spaceport.xyz/", r: "us", g: "portfolio_us_7", s: "web3", d: "Web3 커머스·NFT 인프라", de: "Web3 commerce & NFT infrastructure" },
    { n: "더그림엔터테인먼트", ne: "The Grim Entertainment", u: "https://www.ptjcomics.kr/", r: "kr", g: "portfolio_54", s: "content", d: "웹툰 제작·스튜디오", de: "Webtoon production studio" },
    { n: "AmazeVR", u: "https://amazevr.com/", r: "kr", g: "portfolio_49", s: "content", d: "VR 콘서트·엔터테인먼트", de: "VR concert & entertainment" },
    { n: "아들러", ne: "Adler", u: "https://adler3d.com/", r: "kr", g: "portfolio_48", s: "ai", d: "3D 웹 개발사", de: "3D web development company" },
    { n: "위시켓", ne: "Wishket", u: "https://www.wishket.com/", r: "kr", g: "portfolio_47", s: "commerce", d: "IT 아웃소싱 매칭 플랫폼", de: "IT outsourcing matching platform" },
    { n: "빌드블록", ne: "BuildBlock", u: "https://buildblock.io/", r: "kr", g: "portfolio_46", s: "ai", d: "미국 부동산 및 AI 데이터센터", de: "AI-driven real estate and data center" },
    { n: "메이트랩스", ne: "Matelabs", u: "https://webtoon.today/", r: "kr", g: "portfolio_45", s: "content", d: "웹툰 AI 분석·플랫폼 '오늘의웹툰'", de: "Webtoon AI analytics platform 'Webtoon Today'", a: "오늘의웹툰 webtoon today matelabs" },
    { n: "파인더스에이아이", ne: "Fainders.AI", u: "https://fainders.ai/", r: "kr", g: "portfolio_44_v2", s: "ai", d: "AI 비전 기반 무인 매장 솔루션", de: "AI vision-based unmanned store solution" },
    { n: "버핏서울", ne: "Butfit Seoul", u: "https://www.butfitseoul.com/", r: "kr", g: "portfolio_36", s: "healthcare", d: "그룹 운동·피트니스 커뮤니티", de: "Group workout & fitness community", a: "butfit", hl: 1 },
    { n: "컨텍", ne: "Contec", u: "http://kr.contec.kr/", r: "kr", g: "portfolio_43", s: "ai", d: "우주지상국 서비스 및 위성영상", de: "Spaceport service & satellite video", hl: 1, ho: 5 },
    { n: "Crossangle", u: "https://xangle.io/", r: "kr", g: "portfolio_37", s: "web3", d: "가상자산 공시·리서치 '쟁글'", de: "Crypto disclosure & research 'Xangle'", a: "xangle 쟁글" },
    { n: "KAI MEDIA", u: "https://www.kaimediagroup.com/", r: "kr", g: "portfolio_35", s: "content", d: "미디어·콘텐츠 제작", de: "Media & content production", a: "kai media 카이미디어", hl: 1 },
    { n: "Lagood Company Global", u: "https://www.mybias.me/", r: "kr", g: "portfolio_34_v1", s: "content", d: "멤버십 NFT 기반 Web3 팬 커뮤니티 플랫폼", de: "Membership NFT-based Web3 fan community platform", a: "mybias 마이바이어스" },
    { n: "와드", ne: "WAD", u: "https://app.catchtable.co.kr/", r: "kr", g: "portfolio_42", s: "commerce", d: "레스토랑 예약 플랫폼 '캐치테이블'", de: "Restaurant reservation platform 'CATCHTABLE'", a: "catchtable 캐치테이블", hl: 1, ho: 2 },
    { n: "Loco Interactive Pte. Ltd.", u: "https://loco.gg/", r: "kr", g: "portfolio_41_v2", s: "content", d: "게임 라이브 스트리밍 플랫폼", de: "Game live-streaming platform" },
    { n: "Silverlabs Technologies Inc.", u: "https://rizzle.tv/", r: "kr", g: "rizzle.svg", s: "content", d: "숏폼 비디오 플랫폼", de: "Short-form video platform", a: "rizzle 리즐 실버랩스" },
    { n: "아드리엘", ne: "Adriel", u: "https://www.adriel.com/", r: "kr", g: "portfolio_39", s: "ai", d: "AI 디지털 광고 관리 플랫폼", de: "AI digital advertising management platform" },
    { n: "피알앤디컴퍼니", ne: "PRND Company", u: "https://heydealer.co.kr/", r: "kr", g: "portfolio_33", s: "commerce", d: "중고차 경매 플랫폼 '헤이딜러'", de: "Used-car auction platform 'HEYDEALER'", a: "heydealer 헤이딜러 prnd", hl: 1, ho: 3 },
    { n: "업라이즈", ne: "Uprise", u: "https://www.uprise.financial/", r: "kr", g: "portfolio_32", s: "commerce", d: "디지털 자산 운용·투자 플랫폼", de: "Digital asset management & investment platform" },
    { n: "NABU STUDIO", u: "https://www.metabora.io/", r: "kr", g: "portfolio_10", s: "game", d: "블록체인 게임 스튜디오", de: "Blockchain game studio" },
    { n: "Uplandme", u: "https://www.upland.me/", r: "kr", g: "portfolio_31", s: "web3", d: "메타버스 부동산 블록체인 게임", de: "Metaverse property blockchain game" },
    { n: "콘텐츠랩블루", ne: "Contents Lab Blue", u: "http://contentslabblue.com/", r: "kr", g: "portfolio_30", s: "content", d: "웹툰·콘텐츠 제작", de: "Webtoon & content production" },
    { n: "닥터나우", ne: "Doctornow", u: "https://drnow.co.kr/", r: "kr", g: "portfolio_25", s: "healthcare", d: "비대면 진료·약 배송 플랫폼", de: "Telemedicine & medication delivery platform", a: "drnow doctornow", hl: 1 },
    { n: "벤틀스페이스", ne: "Ventl Space", u: "https://lo-we.kr/", r: "kr", g: "portfolio_24_v1", s: "commerce", d: "뷰티 인프라 플랫폼 기업", de: "Beauty infrastructure platform company" },
    { n: "지구인컴퍼니", ne: "Jiguin Company", u: "https://unlimeat.com/", r: "kr", g: "portfolio_23_v1", s: "commerce", d: "식물성 대체육 '언리미트'", de: "Plant-based alternative meat 'UNLIMEAT'", a: "unlimeat 언리미트" },
    { n: "예스비", ne: "yesbee", u: "https://home.yesbee.com/", r: "kr", g: "portfolio_22", s: "commerce", d: "K-브랜드·IP상품 글로벌 진출 지원 브랜드 액셀러레이터 ", de: "Brand AC for global K-brand and IP expansion" },
    { n: "로드컴플릿", ne: "Load Complete", u: "https://loadcomplete.com/", r: "kr", g: "portfolio_29", s: "game", d: "라이트코어 전략 기반 게임 개발사", de: "lightcore strategy-based game developer" },
    { n: "데이원컴퍼니", ne: "Day1 Company", u: "https://day1company.co.kr/", r: "kr", g: "portfolio_21_v1", s: "ai", d: "성인 교육 콘텐츠(패스트캠퍼스)", de: "Adult education content (Fast Campus)", a: "fastcampus 패스트캠퍼스" },
    { n: "1939 Games", u: "https://www.1939games.com/", r: "kr", g: "portfolio_28", s: "game", d: "전략 게임 개발사", de: "Strategy game developer" },
    { n: "게임테일즈", ne: "Game Tales", u: "https://www.gametales.net/", r: "kr", g: "portfolio_27_v1", s: "game", d: "모바일 및 PC 게임 개발사", de: "Mobile & PC game developer" },
    { n: "Animoca Brands", u: "https://www.animocabrands.com", r: "kr", g: "portfolio_12", s: "web3", d: "글로벌 Web3·블록체인 게임 기업", de: "Global Web3 & blockchain game company", a: "애니모카" },
    { n: "모아이게임즈", ne: "Moai Games", u: "http://moaigames.co.kr/", r: "kr", g: "portfolio_18", s: "game", d: "모바일 게임 개발사", de: "Mobile game developer" },
    { n: "리체", ne: "Liche", u: "https://www.lomad.co.kr/", r: "kr", g: "portfolio_19_v1", s: "commerce", d: "라이프스타일 커머스 플랫폼", de: "Lifestyle commerce platform" },
    { n: "GLASSDOME", u: "https://glassdome.com/", r: "kr", g: "portfolio_6_v2", s: "ai", d: "제조 탄소·ESG 데이터 플랫폼", de: "Manufacturing carbon & ESG data platform" },
    { n: "빅픽처인터렉티브", ne: "Big Picture Interactive", u: "https://www.bigpi.co/", r: "kr", g: "portfolio_17", s: "game", d: "종합 e스포츠 기업", de: "Comprehensive e-sports company", hl: 1, ho: 4 },
    { n: "리짐인터내셔널", ne: "Regime International", u: "https://regime.co.kr/en", r: "kr", g: "portfolio_26_v2", s: "content", d: "종합 엔터테인먼트", de: "Comprehensive entertainment", a: "리짐 regime DPR" },
    { n: "uh2samarket", u: "http://uh2samarket.com/", r: "kr", g: "portfolio_15", s: "commerce", d: " 중국 사입 의류 플랫폼", de: "Online commerce platform for Chinese import fashion" },
    { n: "갤럭시코퍼레이션", ne: "Galaxy Corporation", u: "https://www.galaxyuniverse.ai/", r: "kr", g: "portfolio_16", s: "content", d: "셀럽 IP 기반 엔터테인먼트", de: "Celebrity IP-based entertainment", hl: 1, ho: 1 },
    { n: "Studio Plum", u: "https://www.studioplum.co.kr/ko", r: "kr", g: "portfolio_14", s: "content", d: "종합 엔터테인먼트", de: "Comprehensive entertainment company", a: "스튜디오 플럼" },
    { n: "셀러허브", ne: "SellerHub", u: "https://www.sellerhub.co.kr", r: "kr", g: "portfolio_4", s: "commerce", d: "이커머스 셀러용 도매 소싱 플랫폼", de: "Wholesale sourcing platform for e-commerce sellers" },
    { n: "닫닫닫", ne: "dotdotdot", u: "https://www.dot3company.com/", r: "kr", g: "portfolio_13", s: "content", d: "대화형 AI 솔루션", de: "Conversational AI Solutions" },
    { n: "노머스", ne: "NOMUS", u: "https://www.wonderwall.kr", r: "kr", g: "portfolio_11", s: "content", d: "아티스트 팬덤 커머스·플랫폼", de: "Artist fandom commerce & platform" },
    { n: "Snowprint", u: "https://www.snowprintstudios.com", r: "kr", g: "portfolio_8", s: "game", d: "모바일 전략 게임 개발사(스웨덴)", de: "Mobile strategy game developer (Sweden)", hl: 1, ho: 5 },
    { n: "STUDIO SAMICK", u: "https://www.studiosamick.com/", r: "kr", g: "portfolio_5", s: "commerce", d: "온라인 가구 및 홈퍼니싱 유통 플랫폼", de: "Online furniture & home furnishings e-commerce platform" },
    { n: "에이비제트", ne: "ABZ", u: "https://www.inpock.co.kr", r: "kr", g: "portfolio_7_v1", s: "commerce", d: "크리에이터 커머스 솔루션 '인포크'", de: "Creator commerce solution 'inpock'", a: "inpock 인포크", hl: 1, ho: 4 },
    { n: "MONDAY OFF", u: "https://www.mondayoff.me", r: "kr", g: "portfolio_9", s: "game", d: "하이퍼캐주얼 게임 개발사", de: "Hyper-casual game developer" },
    { n: "ALOHA FACTORY", u: "https://www.aloha-corp.com", r: "kr", g: "portfolio_2", s: "game", d: "캐주얼 모바일 게임 개발사", de: "Casual mobile game developer" },
    { n: "Chartmetric", u: "https://www.chartmetric.com/", r: "kr", g: "portfolio_1", s: "content", d: "음악 스트리밍·소셜 데이터 분석 플랫폼", de: "Music streaming & social data analytics platform" },
    { n: "VALOFE", u: "https://www.valofe.com", r: "kr", g: "portfolio_3", s: "game", d: "글로벌 게임 퍼블리싱·서비스", de: "Global game publishing & services",a: "밸로프", hl: 1, ho: 2 },
];